import "@/assets/css/general.css";
import Header from "@/component/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import StoreProvider from "@/context/StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
